name: Playwright Tests with Allure Reporting

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        browser: [DesktopChrome, DesktopFirefox, DesktopSafari]

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 3: Cache Node.js modules
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 6: Install Allure Command Line
      - name: Install Allure Command Line
        run: npm install -g allure-commandline --save-dev

      # Step 7: Set the BROWSER environment variable
      - name: Set BROWSER environment variable
        run: echo "BROWSER=${{ matrix.browser }}" >> $GITHUB_ENV

      # Step 8: Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test --project=${{ matrix.browser }}
        continue-on-error: true

      # Step 9: Generate Allure Report
      - name: Generate Allure Report
        run: allure generate ./test-report/allure-result --clean -o ./test-results/allure-report

      # Step 10: Upload Allure Report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./test-results/allure-report/
          retention-days: 30
